### ISSUE TITLE
Board member bios still missing: JoAnn Allen, Karina Cervantes, Chris George, Francisco Rojas, Brett Segur. 

### ISSUE THREAD

**Issue by lindabixt** [rskoenig/DigitalNEST#11]
I will ask Jacob to request these Board members submit  brief bios, and have him include a sample bio from another Board member.

Linda Bixby

**Comment by rskoenig** [comment]
Perfect!

**Comment by kirstiscott** [comment]
We are only missing Karina Cervantes now. And, Chris needs to shorten his bio just a bit.

**Comment by rskoenig** [comment]
this is resolved with the new pages
