### ISSUE TITLE
Remove Erica Manfre as a Board member, Add Advisory Board

### ISSUE THREAD

**Issue by lindabixt** [rskoenig/DigitalNEST#12]
Digital NEST Advisory Board
Jess Brown
Hilary Bryant
Bud Colligan
Zach Friend
Mary Lou Goeke
Danny Keith
Kymberly Lacrosse
Courtney Leibrock
Erica Manfre
Brett McFadden
Ralph Miljanich
Donna Murphy
Chris Neklason
Jeremy Neuner
George Ow, Jr.
Margaret Rosas
Kirsti Scott
Matthew Swinnerton
David Terrazas

**Comment by rskoenig** [comment]
Erica is removed. I hacked an implementation for the advisory board. I've told Jason and Rose before, the template is fairly limiting so if we want this displayed differently we'll have to come up with a different way to do it. I'm closing this issue for now, if a new way to list the advisory board is desired let's open a new issue called 'Advisory Board Page/Display.'
