### ISSUE TITLE
Edit Phil's bio

### ISSUE THREAD

**Issue by lindabixt** [rskoenig/DigitalNEST#13]
Hi Manu - we are hoping to include a quote in each Board member's bio. Below is Phil's updated bio, which I'm using as an example for the other board members. I think it's the same number of words as his current bio and should fit! If not please delete the first sentence below and make the second sentence start with Phil instead of He. Thanks! If you have time and inclination, you could edit yours to include a quote if you have anything inspirational to say...totally cool if not. Not everybody needs one.

Phil is a graduate of Santa Clara University. He is an Orchard Operations Analyst for S. Martinelli & Co., supporting the expansion of his family's local apple growing business. Phil says, "A technologically skilled workforce -as envisioned and supported by Digital NEST- is critical to the prosperity of agriculture and the Pajaro Valley. "

**Comment by rskoenig** [comment]
Fits great!
