### ISSUE TITLE
Masthead Lettering removed

### ISSUE THREAD

**Issue by lindabixt** [rskoenig/DigitalNEST#14]
Hi Manu - I know we are deferring a big re-design, but one thing that's for sure is that we are moving "Nurturing Entrepreneurial Skills with Technology" into a much less prominent role, and instead utilizing the shorter tagline "High Tech for Young Minds". I love the new photo and am hoping you can use the shorter tagline in place of the existing text, in a way that doesn't obscure the kids. I've e-mailed you the letterhead so you can get a sense of how it's being positioned with the logo. Can you also add the tagline to the Digital NEST logo at the top? We want to start reinforcing it. Thanks and don't hesitate to check with Jacob on any of this.
Linda

**Comment by rskoenig** [comment]
Text on home page updated. Do you have a horizontal formulation of the logo? Are you sure you want to include "high tech for young minds" both in the navbar with the logo and in the main "hero" section?

**Comment by lindabixt** [comment]
Manu ­ thanks for making that change. I think you know best, and it seems
like you don't think the tagline belongs in the nav bar so that's cool with
me. We just want to start tying it to the name of the org when appropriate,
because it quickly identifies what the org does.

I don't have any graphics except the Digital NEST logo and a separate one of
the 'nest' squiggle.

Jacob - I am copying you to see if you might have what Manu needs, below ­
and if not, if you can ask  whomever is doing the logo design work to create
whatever we need. For my own needs I would like the existing Digital NEST
logo with the High Tech for Young Minds tagline underneath, as in the
attached letterhead. You might want to forward this version to Brett, since
he's using an older letterhead that has the longer the Advisory Board list.

Thanks-
Linda

Linda Bixby  
Nonprofit Development Strategy and Support
831.466.9395 
831.454.6596 mobile

From:  Manu Koenig notifications@github.com
Reply-To:  rskoenig/DigitalNEST
<reply@reply.git
hub.com>
Date:  Monday, November 3, 2014 12:49 AM
To:  rskoenig/DigitalNEST DigitalNEST@noreply.github.com
Cc:  Linda Bixby LindaBixby2@gmail.com
Subject:  Re: [DigitalNEST] Masthead Lettering removed (#14)

Text on home page updated. Do you have a horizontal formulation of the logo?
Are you sure you want to include "high tech for young minds" both in the
navbar with the logo and in the main "hero" section?

‹
Reply to this email directly or view it on GitHub
https://github.com/rskoenig/DigitalNEST/issues/14#issuecomment-61447563 .
{"@context":"http://schema.org","@type":"EmailMessage","description":"View
this Issue on 
GitHub","action":{"@type":"ViewAction","url":"https://github.com/rskoenig/Di
gitalNEST/issues/14#issuecomment-61447563","name":"View Issue"}}

**Comment by kirstiscott** [comment]
Not sure if we need the tagline more than once. It's pretty huge right now, so it would be hard to miss it! If it's for other uses, I'd be happy to create a version of the logo with a tagline.

**Comment by kirstiscott** [comment]
Can we close this?

**Comment by rskoenig** [comment]
yes - looks resolved
