### ISSUE TITLE
simplify newsletter signup form

### ISSUE THREAD

**Issue by rskoenig** [rskoenig/DigitalNEST#17]
Mentioned by Brett Sigur.

**Comment by kirstiscott** [comment]
The signup is currently created by MailChimp. Is there a widget provided by MailChimp that we can install onto the WordPress pages?

**Comment by rskoenig** [comment]
Yeah, mail jump does have such signup widgets. I can look into getting it.

**Comment by rskoenig** [comment]
anyone have the mailchimp login info?

**Comment by kirstiscott** [comment]
diginest
digitalnest20$4

Thanks!

## Kirsti

Scott Design Inc PO Box 758 Capitola CA 95010
Office: 831-531-7766
Skype: kscott.hotdesign
https://www.hotdesign.com

**Comment by rskoenig** [comment]
thanks! this is done - I just made the fields hidden on the mailchimp signup form.
