### ISSUE TITLE
one extra click to donate 

### ISSUE THREAD

**Issue by rskoenig** [rskoenig/DigitalNEST#18]
When I click on "donate" button on the homepage I am directed to a page with another button that says "donate." Only when I click on that am I taken to the page so I can donate online: 
https://secure.acceptiva.com/?cst=33f8bb

There also seems like there could be more we could use acceptiva's landing page for - like maybe a plug for people to make a recurring gift. 

<img width="752" alt="screen shot 2015-12-03 at 10 17 02 am" src="https://cloud.githubusercontent.com/assets/4564957/11569496/115d28f0-99a7-11e5-9507-c494e2b85686.png">

**Comment by lindabixt** [comment]
We can design the donation landing page anyway we like, and can have
multiple pages that we activate/de-activate according to campaigns. We will
refresh all of the donation language/photos at the first of the year and
could easily add a pitch to become a monthly donor.

I agree with you about the current two­step donation process. People should
click donate¹ and be on the donation page. I have raised this before and
was overruled. I still think this is a very necessary change and will more
aggressively push for it when we do the update.
Linda Bixby  
Nonprofit Development Strategy and Support
831.466.9395 
831.454.6596 mobile

From:  Manu Koenig notifications@github.com
Reply-To:  rskoenig/DigitalNEST
<reply+0090c2d1db567cfbb6c64b81aaef87273b2b002ec3521ccd92cf00000001127848d89
2a169ce072aa628@reply.github.com>
Date:  Thursday, December 3, 2015 at 10:15 AM
To:  rskoenig/DigitalNEST DigitalNEST@noreply.github.com
Subject:  [DigitalNEST] one extra click to donate  (#18)

When I click on "donate" button on the homepage I am directed to a page with
another button that says "donate." Only when I click on that am I taken to
the page so I can donate online:
https://secure.acceptiva.com/?cst=33f8bb

There also seems like there could be more we could use acceptiva's landing
page for - like maybe a plug for people to make a recurring gift.

 <https://cloud.githubusercontent.com/assets/4564957/11569450/d2ef2a5a-99a6-
11e5-9a83-0a26b9211508.png>


Reply to this email directly or view it on GitHub
https://github.com/rskoenig/DigitalNEST/issues/18 .

**Comment by rskoenig** [comment]
This is true of all of the metaslider carousel images as well. Let's see if
we can evaluate the metrics currently (views of those pages vs.
signups/form submissions) and then implement a change.
