### ISSUE TITLE
remove "Honors for our award-winning website!" (?)

### ISSUE THREAD

**Issue by rskoenig** [rskoenig/DigitalNEST#19]
This seems cheesy to me - the nicest sites generally don't need to advertise that they have received awards on the site itself - maybe on the product/service that the site is advertising.

**Comment by lindabixt** [comment]
I¹d suggest taking this up with the website team/Jacob.
Linda Bixby  
Nonprofit Development Strategy and Support
831.466.9395 
831.454.6596 mobile

From:  Manu Koenig notifications@github.com
Reply-To:  rskoenig/DigitalNEST
<reply+0090c2d1e27ef0966309bba1b7c7a1aaaa501b364ebfccd692cf0000000112784c4a9
2a169ce072ab1ce@reply.github.com>
Date:  Thursday, December 3, 2015 at 10:30 AM
To:  rskoenig/DigitalNEST DigitalNEST@noreply.github.com
Subject:  [DigitalNEST] remove "Honors for our award-winning website!" ?
(#19)

This seems cheesy to me - the nicest sites generally don't need to advertise
that they have received awards on the site itself - maybe on the
product/service that the site is advertising.


Reply to this email directly or view it on GitHub
https://github.com/rskoenig/DigitalNEST/issues/19 .

**Comment by rskoenig** [comment]
yup, was intending to discuss with you all today

**Comment by kirstiscott** [comment]
How about if we make this a news article?
