### ISSUE TITLE
member constitution 

### ISSUE THREAD

**Issue by rskoenig** [rskoenig/DigitalNEST#20]
Have the members write their own code of conduct/ purpose/ etc that new members sign.

**Comment by rskoenig** [comment]
The current sign up form references a code of conduct, but it is lite: 
http://digitalnest.org/wp-content/uploads/Digital-NEST-Membership-Form.pdf

**Comment by lindabixt** [comment]
Hey Manu- Can you remove me from this distribution list?
Thanks- 
Linda

**Comment by rskoenig** [comment]
I think you have to click "Unwatch" next to the "Star" button in the top
right on this page:
https://github.com/rskoenig/DigitalNEST/issues

If you change your status to "Not Watching" (as opposed to "Ignoring") you
will still receive a notification when mentioned @lindabixt
