### ISSUE TITLE
Update 'About' section

### ISSUE THREAD

**Issue by rskoenig** [rskoenig/DigitalNEST#3]

**Comment by rskoenig** [comment]
Linda, if you send me the content you want for the about us page I'll post it.

**Comment by lindabixt** [comment]
Not written yet ­ will send you everything as it gets done. You are on it,
Manu!
LB
Linda Bixby  
Nonprofit Development Strategy and Support
831.466.9395 
831.454.6596 mobile

From:  Manu Koenig notifications@github.com
Reply-To:  rskoenig/DigitalNEST
<reply@reply.git
hub.com>
Date:  Friday, October 31, 2014 2:33 PM
To:  rskoenig/DigitalNEST DigitalNEST@noreply.github.com
Cc:  Linda Bixby LindaBixby2@gmail.com
Subject:  Re: [DigitalNEST] Update 'About' section (#3)

Linda, if you send me the content you want for the about us page I'll post
it.

‹
Reply to this email directly or view it on GitHub
https://github.com/rskoenig/DigitalNEST/issues/3#issuecomment-61334634 .
{"@context":"http://schema.org","@type":"EmailMessage","description":"View
this Issue on 
GitHub","action":{"@type":"ViewAction","url":"https://github.com/rskoenig/Di
gitalNEST/issues/3#issuecomment-61334634","name":"View Issue"}}

**Comment by kirstiscott** [comment]
Until we have content for a real ABOUT page, I am taking it off the menu.
