### ISSUE TITLE
Blog visibility/ schedule

### ISSUE THREAD

**Issue by rskoenig** [rskoenig/DigitalNEST#6]
"Blog" - last post was a month ago. Let’s add the piece from Tech Crunch

**Comment by kirstiscott** [comment]
Can you send me links to everything we should add?

**Comment by kirstiscott** [comment]
I renamed the categories so there is no longer an "uncategorized" option. I also added the donation widget to the sidebar. Let me know if it's too much!

**Comment by rskoenig** [comment]
Changed "What's New?" on the home page to "From the Blog" went to add a blog to the "About" tab but noticed we have a press link there - too similar to add both(?)

Let's also make sure that numerous people are contributing to the blog. Is there a spreadsheet for this already or should we create something?
