### ISSUE TITLE
Comments turned off for posts?

### ISSUE THREAD

**Issue by rskoenig** [rskoenig/DigitalNEST#7]

**Comment by kirstiscott** [comment]
I think that we need to have comments on for all posts. Is there any spam filter on this site? Akismet?

**Comment by rskoenig** [comment]
Don't know - we're definitely getting a lot of spam comments right now though...

**Comment by kirstiscott** [comment]
It looks like there's a spam blocker. Nothing gets through unless it's moderated, right?
I just went through them yesterday and marked all but one as spam.

**Comment by kirstiscott** [comment]
I just enabled comments on the blog posts. Let's see if it creates a huge amount of spam or problems, and if so, let's turn it off again! You can close this issue if that's ok with you! Thanks! Kirsti

**Comment by rskoenig** [comment]
looks good to me, feel free to close these yourself!

**Comment by kirstiscott** [comment]
I don’t think I have permissions to close items

Thanks!

## Kirsti

Scott Design Inc PO Box 758 Capitola CA 95010
Office: 831-531-7766
Skype: kscott.hotdesign
https://www.hotdesign.com
