### ISSUE TITLE
visibility of Calendar

### ISSUE THREAD

**Issue by rskoenig** [rskoenig/DigitalNEST#9]
Or at least a link to the open house.

**Comment by kirstiscott** [comment]
Is there a page somewhere online for this open house that we could link to?

**Comment by kirstiscott** [comment]
And, is there a plan to put a calendar? Does this theme have a calendar function? Would you use an external calendar site?

**Comment by rskoenig** [comment]
The event page is the facebook event:
https://www.facebook.com/events/271490589641359/

Haven't explored whether the theme natively supports a calendar function or otherwise how to do it.

**Comment by kirstiscott** [comment]
I think this should be part of a discussion with Jacob on how he wants to handle sign ups for classes, etc. It may be that we use Event Brite and then we embed their widgets on the site. I'll send an email to Jacob and see what he's thinking. You can close this issue until then. Thanks!

**Comment by rskoenig** [comment]
checking the schedule page and don't see a calendar, so assume that we don't have one yet...
http://digitalnest.org/what-we-do/schedule/

**Comment by rskoenig** [comment]
never mind, finally found the calendar below Gabriel's post - this should definitely be above the fold
